import ChakraProviders from '@/contexts/Chakra.context'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}
interface Props {
  children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body>
        <ChakraProviders>{children}</ChakraProviders>
      </body>
    </html>
  )
}
